primary_menu:
  items:
    - title: galerie
      link: "#"
      in_active_trail: true
    - title: kollektionen
      link: "#"
    - title: shop
      link: "#"
      icon: arrow-up
    - title: kontakt
      link: "#"
